### ISSUE TITLE
Missing cursor on rendered tree command line

### ISSUE THREAD

**Issue by simonkeyd** [Yukuro/hugo-theme-shell#27]
**Describe the bug**
Cool theme ! Smol bug the 'tree' command is missing the end of line cursor

**To Reproduce**
Render using the following basic `config.toml` :
```toml
  [Params.Tree]
  use = true
  folderName = "my_activity"
  files = [ 
    ["foo", "https://www.example.com/"],
  ]
```

**Desktop (please complete the following information):**
 - OS: arch
 - Browser firefox
 - Version 97.0
